# Trigger the workflow on milestone events
name: Milestone Closure

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
      
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Update CHANGELOG
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          token: ${{secrets.CHANGELOG_TOKEN}}
          tag: v0.0.7

      - name: Commit CHANGELOG.md
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: master
          commit_message: 'docs: update CHANGELOG.md for ${{ github.ref_name }} [skip ci]'
          file_pattern: CHANGELOG.md
