# Trigger the workflow on milestone events
on:
  milestone:
    types: [closed]
name: Milestone Closure
jobs:
  create-release-notes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: "Build Changelog"
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v3
        env:
            GITHUB_TOKEN: ${{secrets.CHANGELOG_TOKEN}}
      - run: echo ${{steps.build_changelog.outputs.changelog}}
            echo ${{steps.build_changelog.outputs.failed}}
            echo ${{steps.build_changelog.outputs.pull_requests}}
